name: CloudWrap Backend CD

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/backend-cd.yml
      - backend/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Restart PM2 application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/CloudWrap
            git pull origin main
            cd backend
            npm install --production
            pm2 reload all || pm2 start server.js
