name: CloudWrap Backend CD

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/backend-cd.yml
      - backend/

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Keys
        run: |
          mkdir -p ~/.ssh 
          echo "${{secrets.EC2_SSH_KEY}}" > ~/.ssh/sg-guanhua-mbp.pem
          chmod 400 ~/.ssh/sg-guanhua-mbp.pem
          ssh-keyscan -H ec2-13-127-108-110.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Access the EC2 server
        run: |
          ssh -i ~/.ssh/sg-guanhua-mbp.pem ubuntu@ec2-13-127-108-110.ap-south-1.compute.amazonaws.com << 'EOF'
            cd ~/CloudWrap
            git pull origin main
            cd backend
            npm install --production
            pm2 restart app || npm start
          EOF
